---
spring:
  cloud:
    config:
      server:
        git:
          uri:  file:///Z:/spring-cloud-config
          #uri: https://github.com/kennyk65/Microservices-With-Spring-Student-Files
          #proxy:
          #  https:
          #    host: proxy.fazenda.mg.gov.br
          #    password: senha123#
          #    port: '8003'
          #    username: vander.vale
          #    nonProxyHosts: example.com
          searchPaths: ConfigData
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001

  